# devlm-identity/config/config.yaml

server:
  port: 8080
  host: "0.0.0.0"

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}

jwt:
  secret_key: ${JWT_SECRET_KEY}
  refresh_secret_key: ${JWT_REFRESH_SECRET_KEY}
  access_token_expiry: "15m"
  refresh_token_expiry: "7d"

logging:
  level: "debug"
  format: "json"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "https://devlm.example.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"
  allowed_headers:
    - "Content-Type"
    - "Authorization"

rate_limiting:
  requests_per_minute: 60

ssh:
  max_keys_per_user: 5